# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cellphone', models.CharField(blank=True, max_length=17, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, null=True)),
                ('excluded', models.BooleanField(default=False)),
                ('excluded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
