# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
