# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='excluded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
