# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 22, 285348, tzinfo=utc), verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='excluded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=True, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Entregue'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 11, 39, 22, 285308, tzinfo=utc), verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pre\xe7o de Venda'),
        )

    ]
