# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180326_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 0, 8, 16, 428313, tzinfo=utc), verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 0, 8, 16, 428313, tzinfo=utc), verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_form',
            field=models.IntegerField(blank=True, choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'Dinheiro')], null=True, verbose_name='Forma de pagamento'),
        ),
    ]
