# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180313_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 49, 7, 610449, tzinfo=utc), verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 49, 7, 610378, tzinfo=utc), verbose_name='Data do Pedido'),
        ),
    ]
